---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 770416131081330688-fSyIbyaLicWKvD8GwYrGJhRWEiwWV8N
:access_token_secret: 7SfXekrysxVFFKLIcncZGHZttMbXUFzDmJKdOdgSN0Zam
